name: Azure Files mount
on:
  workflow_dispatch:

jobs:
  mount-azure-drive:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -y cifs-utils netcat
          nc -zvw3 ababushk.file.core.windows.net 445

          sudo mkdir -p $MNT_PATH
          sudo mount -t cifs //ababushk.file.core.windows.net/githubactionsccache $MNT_PATH -o username=$STORAGE_ACCOUNT_NAME,password=$STORAGE_ACCOUNT_KEY,serverino,nosharesock,actimeo=30,mfsymlinks

          echo "Hello world" > $MNT_PATH/testfile

        env:
          RESOURCE_GROUP_NAME: 'Azure-test'
          STORAGE_ACCOUNT_NAME: 'ababushk'
          STORAGE_ACCOUNT_KEY: ${{ secrets.OPENVINO_AZURE_STORAGE_ACCOUNT_KEY }}
          FILE_SHARE_NAME: 'githubactionsccache'
          MNT_ROOT: '/mount'
          MNT_PATH: '$MNT_ROOT/$STORAGE_ACCOUNT_NAME/$FILE_SHARE_NAME'