name: Azure Files mount
on:
  workflow_dispatch:

jobs:
  mount-azure-drive:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install -y cifs-utils

          sudo mkdir -p $MNT_PATH
          sudo mount -t cifs //${STORAGE_ACCOUNT_NAME}.file.core.windows.net/${FILE_SHARE_NAME}/ccache $MNT_PATH/ccache -o username=$STORAGE_ACCOUNT_NAME,password=$STORAGE_ACCOUNT_KEY,serverino,nosharesock,actimeo=30,mfsymlinks,uid=$(id -u),gid=$(id -g)

          echo "Hello world" > $MNT_PATH/hello_file.txt
          dd if=/dev/urandom of=$MNT_PATH/testfile.bin bs=1M count=50
        env:
          RESOURCE_GROUP_NAME: 'GithubActions'
          STORAGE_ACCOUNT_NAME: 'gacaches'
          STORAGE_ACCOUNT_KEY: ${{ secrets.AZURE_CACHES_STORAGE_ACCOUNT_KEY }}
          FILE_SHARE_NAME: 'githubactionsccache'
          MNT_ROOT: '/mount'
          MNT_PATH: '$MNT_ROOT/$STORAGE_ACCOUNT_NAME/$FILE_SHARE_NAME'